### ISSUE TITLE
Move items from a previous sprint's backlog and in-progress to the next sprints icebox when it is closed

### ISSUE THREAD

**Issue by yarneo** [material-foundation/material-automation#6]

**Comment by jverkoey** [comment]
Some limitations I'm worried we'll run into here:

1. I don't think there's a way to "clone" a GitHub Project with the GitHub API in the same way that you can do from the GitHub web UI. Mainly, there is no way to copy automation.
2. I don't think there are *any* GitHub APIs for configuring automation.
3. I don't think there is an API for adding an issue to a Project's triage queue — I think you can only add issues as cards.

Given the above, it's distinctly possible that we may want to explore the creation of a Chrome extension that does the work for us rather than a command on the Material Automation server. The Chrome extension would do the following:

1. Clone the current project.
2. Close the current project.
3. For each issue in the current project, open a new tab, add the issue to the new sprint using the web UI, and then close the tab.

@gk11 may have some insight into how we might best do this?

**Comment by yarneo** [comment]
Agreed with all the current limitations. The project API is still in preview mode so it is a bit lacking.

@jverkoey a few follow up questions:
1. is there anything in the automation of the project that is hard to recreate if a new project is created with the same 3 columns just the automation needs to be added?
2. How do you feel about having a Triage/Icebox column in the sprint (similar to the internal sprint). Or alternatively add them initially to the backlog and remove them if unneeded, it seems like there is much more adding than actually removing. Also removing can be done from the project page and there is no need to go into every issue.

**Comment by jverkoey** [comment]
Ah interesting. The automation isn't super hard to set up, but it's easy to get wrong because of all the sub-options, so we'd need to probably include screenshots showing how to fully configure the project.

An icebox column works fine as well! I had been trying to simplify the project board by using GitHub's existing facilities (i.e. the triage list), but if having a triage column makes automation easier than that would be reasonable to do. We could add a card to the triage column saying "delete me once you've finished planning the sprint" :P

**Comment by jverkoey** [comment]
Oh! We could just add some cards to the project saying "Configure this column in this manner" with specific instructions.

**Comment by yarneo** [comment]
true! ok ill get started on this. Let me know if you have any preference on what the "Icebox" column should be named
